"""Extract the pieces of the hybrid5 Qwen runner that the A100 harness reuses verbatim (docs/A100_PLAN.md, step 2).

The prompt, grid parser, tool-call replay and the Python tool sandbox must be byte-identical to production, so they are
copied out of the built hybrid5 notebook instead of being rewritten. The scheduler, deadlines, forced-final turn and
recovery are left behind on purpose; a100/qwen_ab.py replaces them with a fixed total-token budget.

    uv run --no-project python scripts/build_a100_harness.py
Output: a100/runner_parts.py
"""
import ast
import hashlib
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
NB = ROOT / "kaggle" / "arc2-hybrid5-nvarc-qwen38-medium" / "arc2-hybrid5-nvarc-qwen38-medium.ipynb"
OUT = ROOT / "a100" / "runner_parts.py"

ASSIGNS = ["RUNTIME_CONFIG", "AGGREGATOR_SOURCE", "SANDBOX_SOURCE"]
FUNCS = ["load_module_from_source", "stable_sample_seed", "select_distinct_fallback","parse_model_grid", "response_reasoning",
         "assistant_replay_message", "decode_tool_code", "tool_wall_budget_seconds", "render", "build_agent_prompt",
         "build_prompt"]

cells = json.load(open(NB, encoding="utf-8"))["cells"]
src = next("".join(c["source"]) for c in cells if "".join(c["source"]).startswith("%%writefile /kaggle/working/qwen_runner.py"))
src = src.split("\n", 1)[1]
tree = ast.parse(src)

found = {}
for node in tree.body:
    if isinstance(node, ast.Assign) and len(node.targets) == 1 and getattr(node.targets[0], "id", None) in ASSIGNS:
        found[node.targets[0].id] = ast.get_source_segment(src, node)
    elif isinstance(node, ast.FunctionDef) and node.name in FUNCS:
        found[node.name] = ast.get_source_segment(src, node)
missing = [n for n in ASSIGNS + FUNCS if n not in found]
assert not missing, f"not found in runner: {missing}"

header = f'''"""Verbatim parts of the hybrid5 Qwen runner (generated by scripts/build_a100_harness.py; do not edit).

source: {NB.relative_to(ROOT).as_posix()}  sha256(runner)={hashlib.sha256(src.encode()).hexdigest()[:16]}
"""
import hashlib, importlib.util, json, re, sys
from pathlib import Path

'''
body = "\n\n".join(found[n] for n in ASSIGNS + FUNCS)
OUT.parent.mkdir(exist_ok=True)
OUT.write_text(header + body + "\n", encoding="utf-8")
ast.parse(OUT.read_text(encoding="utf-8"))
print(f"wrote {OUT.relative_to(ROOT)}: {', '.join(ASSIGNS + FUNCS)}")
